---
# tasks file for NextCloud
- name: Launch container NextCloud
  command: docker run -d --name nextcloud -p 8080:80 --restart unless-stopped -v apps:/var/www/html/custom_apps -v config:/var/www/html/config -v data:/var/www/data -v nextcloud:/var/www/html nextcloud
  tags:
    - docker_nextcloud